### PR TITLE
allow to import null value

### PR DESCRIPTION
**Pull request by torhoehn**
Please make sure these boxes are checked before submitting your PR - thank you!

- [ ] Pull request is based against develop branch
- [ ] README.md reflects changes (if applicable)
- [ ] New files contain a license header

### Issue

This PR fixes issue #54.

### Proposed changes

...

### CODE REVIEW

**Comment by ktomk** [comment]
Just to confirm this patch, but not without saying: this was a recent change, the resolver could return null as well if this is the intended behaviour.

Then this implementation detail (likely an oversight) would not need to bubble up.

Thanks for the report(s)!

**Comment by torhoehn** [comment]
@ktomk I'll recheck this tomorrow.

**Comment by ktomk** [comment]
@torhoehn: in regards to me you *never* have to hurry for anything. Take your time and thanks again!

**Comment by torhoehn** [comment]
@ktomk I updated the PR. Is this fine for you or did you mean something else?

**Pull request closed without merging**
