### PR TITLE
Fix unresolveable codes.

### PR DESCRIPTION
**Pull request by tkn98**
Resolve codes as codes, not IDs. Looks like a new Magento 2 version does
not resolve codes "via IDs" any longer.

@therouv Please check and if it works for you, too, please merge and tag - Danke :)

### CODE REVIEW

**Comment by therouv** [comment]
Hi @tkn98 which Magento version are you referring to? 
Can you also provide a sample yaml file?

I just tested it with Magento CE 2.1.2 and there seems to be no problem.

**Comment by tkn98** [comment]
Magento version should be very recent, it's a development project in which we keep current (so should be EE 2.1.2, I can't verify the exact version right now quickly).

In production mode and with a clean build.

You can find [the 2.1.2-patch3 tag in the Netz98 fork](https://github.com/netz98/Magento2-ConfigImportExport/tree/2.1.2-patch3), that's the version we have in use (just what this PR is).

To trigger the error you need to use the store-code/website-code instead of the numeric ID, a sample file would depend on your local setup of the store. 

Example `payment.yaml`:

```
#########
# payment
#########

payment/example_creditcard/active:
  websites:
    example_site_de: 1
    example_site_at: 1
```

**Comment by therouv** [comment]
Hi @tkn98 just merged your changes and tagged a new release. Thanks for your contribution.

I couldn't reproduce the error on EE 2.1.2 even with store code/website code in the yaml file. But your changes definitely make sense, so I merged them :)

**Comment by tkn98** [comment]
Well I could reproduce this always even across systems. And by looking into the code I could see that core Magento did not reveal from codes any longer by those methods.

I can see the tag is 2.2.0 then, right?

Thanks for merging.

**Pull request merged**
