### PR TITLE
Magento 2.2 and PHP 7.1 support

### PR DESCRIPTION
**Pull request by sweikenb**
Please make sure these boxes are checked before submitting your PR - thank you!

- [x] Pull request is based against develop branch
- [x] README.md reflects changes (if applicable)
- [x] New files contain a license header

### Issue

This PR fixes issue #19 .

### Proposed changes

I added the Magento 2.2 and PHP 7.1 compatibility including fixed PhpUnit tests for PhpUnit 6.2.

**ATTENTION:**
As these changes contain BC breaks (due to changed composer requirements), I highly recommend releasing this PR in/as next version 3.0.0

### CODE REVIEW

**Comment by mwr** [comment]
+1

**Comment by mwr** [comment]
@therouv any update on this one?

**Comment by therouv** [comment]
Released as 3.0.0. Thanks @sweikenb :-)

**Comment by mwr** [comment]
Great thanks (=

**Pull request merged**
